"""Baseline schema - captures all existing tables.

Revision ID: 001_baseline
Revises:
Create Date: 2026-02-03

This migration captures the existing database schema as a baseline.
For existing databases, run: alembic stamp 001_baseline
For new databases, run: alembic upgrade head
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Users table ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('honorific', sa.String(length=10), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=False, server_default='user'),
        sa.Column('password_reset_token', sa.String(length=100), nullable=True),
        sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
        sa.Column('academic_qualifications', sa.Text(), nullable=True),
        sa.Column('membership_level', sa.String(length=100), nullable=True),
        sa.Column('membership_number', sa.String(length=100), nullable=True),
        sa.Column('professional_designation', sa.String(length=200), nullable=True),
        sa.Column('panel_valuer_banks', sa.JSON(), nullable=True),
        sa.Column('house_number', sa.String(length=50), nullable=True),
        sa.Column('area_development', sa.String(length=100), nullable=True),
        sa.Column('village', sa.String(length=100), nullable=True),
        sa.Column('locality', sa.String(length=100), nullable=True),
        sa.Column('phone_primary', sa.String(length=50), nullable=True),
        sa.Column('phone_secondary', sa.String(length=50), nullable=True),
        sa.Column('office_department', sa.String(length=200), nullable=True),
        sa.Column('office_region', sa.String(length=100), nullable=True),
        sa.Column('office_street_city', sa.String(length=200), nullable=True),
        sa.Column('office_phone', sa.String(length=50), nullable=True),
        sa.Column('preferred_letterhead_template', sa.String(length=50), nullable=True, server_default='classic'),
        sa.Column('bank_accounts', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    # ### Vehicles table (created before reports due to FK dependency) ###
    op.create_table('vehicles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'),
        sa.Column('vehicle_type', sa.String(length=50), nullable=True),
        sa.Column('is_template', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('is_deleted', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('original_vehicle_id', sa.Integer(), nullable=True),
        sa.Column('registration_number', sa.String(length=50), nullable=True),
        sa.Column('provincial_council', sa.String(length=100), nullable=True),
        sa.Column('class_of_vehicle', sa.String(length=100), nullable=True),
        sa.Column('body_colour', sa.String(length=100), nullable=True),
        sa.Column('chassis_number', sa.String(length=100), nullable=True),
        sa.Column('engine_number', sa.String(length=100), nullable=True),
        sa.Column('vehicle_status', sa.String(length=100), nullable=True),
        sa.Column('country_of_origin', sa.String(length=100), nullable=True),
        sa.Column('make', sa.String(length=100), nullable=True),
        sa.Column('model', sa.String(length=200), nullable=True),
        sa.Column('date_of_first_registration', sa.String(length=50), nullable=True),
        sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
        sa.Column('cylinder_capacity', sa.Integer(), nullable=True),
        sa.Column('fuel_type', sa.String(length=50), nullable=True),
        sa.Column('mileage', sa.Integer(), nullable=True),
        sa.Column('mileage_unit', sa.String(length=20), nullable=True, server_default='km'),
        sa.Column('engine_type', sa.String(length=100), nullable=True),
        sa.Column('transmission', sa.String(length=50), nullable=True),
        sa.Column('wheel_drive', sa.String(length=20), nullable=True),
        sa.Column('running_condition', sa.String(length=50), nullable=True),
        sa.Column('clutch_status', sa.String(length=100), nullable=True),
        sa.Column('engine_condition', sa.String(length=50), nullable=True),
        sa.Column('gear_box_condition', sa.String(length=50), nullable=True),
        sa.Column('differential_status', sa.String(length=100), nullable=True),
        sa.Column('gear_selection', sa.String(length=50), nullable=True),
        sa.Column('body_condition', sa.String(length=50), nullable=True),
        sa.Column('chassis_condition', sa.String(length=50), nullable=True),
        sa.Column('upholstery_condition', sa.String(length=50), nullable=True),
        sa.Column('underside_condition', sa.String(length=50), nullable=True),
        sa.Column('body_parts_status', sa.String(length=100), nullable=True),
        sa.Column('engine_parts_status', sa.String(length=100), nullable=True),
        sa.Column('accessories_status', sa.String(length=100), nullable=True),
        sa.Column('fuel_consumption', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('fuel_consumption_unit', sa.String(length=20), nullable=True),
        sa.Column('foot_brake_condition', sa.String(length=50), nullable=True),
        sa.Column('disc_brake_available', sa.Boolean(), nullable=True),
        sa.Column('parking_brake_condition', sa.String(length=50), nullable=True),
        sa.Column('abs_available', sa.Boolean(), nullable=True),
        sa.Column('features', sa.JSON(), nullable=True),
        sa.Column('suspension', sa.JSON(), nullable=True),
        sa.Column('tyres', sa.JSON(), nullable=True),
        sa.Column('electrical', sa.JSON(), nullable=True),
        sa.Column('lights', sa.JSON(), nullable=True),
        sa.Column('has_accidents', sa.Boolean(), nullable=True),
        sa.Column('has_repairs', sa.Boolean(), nullable=True),
        sa.Column('needs_repairs_within_year', sa.Boolean(), nullable=True),
        sa.Column('body_parts_replaced', sa.Boolean(), nullable=True),
        sa.Column('purchase_price', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('brand_new_price', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('market_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('forced_sale_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_summary', sa.Text(), nullable=True),
        sa.Column('office_data', sa.JSON(), nullable=True),
        sa.Column('past_valuations', sa.JSON(), nullable=True),
        sa.Column('vehicle_photos', sa.JSON(), nullable=True),
        sa.Column('book_images', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['original_vehicle_id'], ['vehicles.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'registration_number', name='uq_vehicle_user_registration')
    )
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_make'), 'vehicles', ['make'], unique=False)
    op.create_index(op.f('ix_vehicles_registration_number'), 'vehicles', ['registration_number'], unique=False)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)

    # ### Reports table ###
    op.create_table('reports',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('report_type', sa.String(length=100), nullable=False, server_default='residential_property'),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'),
        sa.Column('lot_number', sa.String(length=200), nullable=True),
        sa.Column('plan_number', sa.String(length=100), nullable=True),
        sa.Column('plan_date', sa.String(length=50), nullable=True),
        sa.Column('licensed_surveyor_name', sa.String(length=255), nullable=True),
        sa.Column('property_identification_type', sa.String(length=50), nullable=True),
        sa.Column('property_identification_documents', sa.JSON(), nullable=True),
        sa.Column('applicant_title', sa.String(length=20), nullable=True),
        sa.Column('applicant_full_name', sa.String(length=500), nullable=True),
        sa.Column('applicant_id_type', sa.String(length=50), nullable=True),
        sa.Column('applicant_id_number', sa.String(length=100), nullable=True),
        sa.Column('applicant_address_line1', sa.String(length=500), nullable=True),
        sa.Column('applicant_address_line2', sa.String(length=500), nullable=True),
        sa.Column('applicant_district', sa.String(length=100), nullable=True),
        sa.Column('applicant_province', sa.String(length=100), nullable=True),
        sa.Column('applicant_country', sa.String(length=100), nullable=True, server_default='Sri Lanka'),
        sa.Column('request_type', sa.String(length=50), nullable=True),
        sa.Column('applicant_contact_number', sa.String(length=50), nullable=True),
        sa.Column('valuation_type', sa.String(length=100), nullable=True),
        sa.Column('property_type_valued', sa.String(length=200), nullable=True),
        sa.Column('valuation_purpose', sa.String(length=200), nullable=True),
        sa.Column('has_additional_owner', sa.String(length=10), nullable=True),
        sa.Column('additional_owner_names', sa.Text(), nullable=True),
        sa.Column('has_deed_info', sa.String(length=10), nullable=True),
        sa.Column('deeds', sa.JSON(), nullable=True),
        sa.Column('submission_organization', sa.Text(), nullable=True),
        sa.Column('submission_address', sa.Text(), nullable=True),
        sa.Column('submission_recipient_position', sa.String(length=200), nullable=True),
        sa.Column('inspection_date', sa.String(length=50), nullable=True),
        sa.Column('has_special_note', sa.String(length=10), nullable=True),
        sa.Column('special_note_text', sa.Text(), nullable=True),
        sa.Column('report_reference', sa.String(length=100), nullable=True),
        sa.Column('report_date', sa.String(length=50), nullable=True),
        sa.Column('use_applicant_address_as_property', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('assessment_number', sa.String(length=100), nullable=True),
        sa.Column('property_village', sa.String(length=200), nullable=True),
        sa.Column('property_divisional_secretariat', sa.String(length=200), nullable=True),
        sa.Column('property_district', sa.String(length=100), nullable=True),
        sa.Column('property_province', sa.String(length=100), nullable=True),
        sa.Column('property_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('property_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('property_number', sa.String(length=50), nullable=True),
        sa.Column('grama_niladari_division', sa.String(length=200), nullable=True),
        sa.Column('hathpaththuwa', sa.String(length=300), nullable=True),
        sa.Column('korale', sa.String(length=300), nullable=True),
        sa.Column('pradeshiya_sabha', sa.String(length=200), nullable=True),
        sa.Column('ward_number', sa.String(length=20), nullable=True),
        sa.Column('is_municipal_limit', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('location_direction', sa.String(length=50), nullable=True),
        sa.Column('access_starting_point_name', sa.Text(), nullable=True),
        sa.Column('access_starting_point_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('access_starting_point_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('access_route_data', sa.JSON(), nullable=True),
        sa.Column('access_directions_text', sa.Text(), nullable=True),
        sa.Column('access_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('access_duration_minutes', sa.Integer(), nullable=True),
        sa.Column('access_road_type', sa.String(length=200), nullable=True),
        sa.Column('property_road_position', sa.String(length=100), nullable=True),
        sa.Column('location_map_image_data', sa.Text(), nullable=True),
        sa.Column('access_road_conditions', sa.JSON(), nullable=True),
        sa.Column('access_entry_mode', sa.String(length=20), nullable=True),
        sa.Column('access_road_classes_detected', sa.JSON(), nullable=True),
        sa.Column('land_extent_acres', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('land_extent_roods', sa.Integer(), nullable=True),
        sa.Column('land_extent_perches', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('land_extent_hectares', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('land_extent_square_meters', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('land_extent_formatted', sa.String(length=50), nullable=True),
        sa.Column('land_traditional_name', sa.String(length=300), nullable=True),
        sa.Column('boundaries', sa.JSON(), nullable=True),
        sa.Column('physical_boundaries_types', sa.JSON(), nullable=True),
        sa.Column('physical_boundaries_description', sa.Text(), nullable=True),
        sa.Column('boundary_types_per_direction', sa.JSON(), nullable=True),
        sa.Column('entrance_type', sa.String(length=100), nullable=True),
        sa.Column('boundaries_summary_text', sa.Text(), nullable=True),
        sa.Column('has_multiple_lots', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('lots_data', sa.JSON(), nullable=True),
        sa.Column('uploaded_documents', sa.JSON(), nullable=True),
        sa.Column('field_sources', sa.JSON(), nullable=True),
        sa.Column('survey_plan_scale', sa.String(length=50), nullable=True),
        sa.Column('plan_reference_notes', sa.Text(), nullable=True),
        sa.Column('land_shape', sa.String(length=50), nullable=True),
        sa.Column('land_type', sa.String(length=50), nullable=True),
        sa.Column('land_frontage_type', sa.String(length=100), nullable=True),
        sa.Column('land_frontage_width', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('land_frontage_description', sa.Text(), nullable=True),
        sa.Column('land_level', sa.String(length=50), nullable=True),
        sa.Column('land_level_difference', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('soil_type', sa.String(length=50), nullable=True),
        sa.Column('water_table_depth', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('flood_risk', sa.String(length=50), nullable=True),
        sa.Column('inundation_risk', sa.String(length=50), nullable=True),
        sa.Column('earth_slip_risk', sa.String(length=50), nullable=True),
        sa.Column('land_condition', sa.String(length=50), nullable=True),
        sa.Column('land_condition_description', sa.Text(), nullable=True),
        sa.Column('land_description_text', sa.Text(), nullable=True),
        sa.Column('ongoing_construction_notes', sa.Text(), nullable=True),
        sa.Column('elevation_changes', sa.String(length=50), nullable=True),
        sa.Column('drainage_pattern', sa.String(length=50), nullable=True),
        sa.Column('vegetation_type', sa.String(length=50), nullable=True),
        sa.Column('natural_features', sa.Text(), nullable=True),
        sa.Column('buildings', sa.JSON(), nullable=True),
        sa.Column('occupier_name', sa.String(length=300), nullable=True),
        sa.Column('occupier_relationship', sa.String(length=50), nullable=True),
        sa.Column('property_photos', sa.JSON(), nullable=True),
        sa.Column('distance_to_major_town_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('major_town_name', sa.String(length=200), nullable=True),
        sa.Column('nearby_facilities', sa.JSON(), nullable=True),
        sa.Column('has_electricity', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('water_supply_type', sa.JSON(), nullable=True),
        sa.Column('telecommunication_types', sa.JSON(), nullable=True),
        sa.Column('internet_types', sa.JSON(), nullable=True),
        sa.Column('has_public_transport', sa.Boolean(), nullable=True),
        sa.Column('public_transport_routes', sa.Text(), nullable=True),
        sa.Column('public_transport_frequency', sa.String(length=200), nullable=True),
        sa.Column('nearest_bus_stop_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('nearest_bus_stop_name', sa.String(length=200), nullable=True),
        sa.Column('nearest_railway_station', sa.String(length=200), nullable=True),
        sa.Column('nearest_railway_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('area_type', sa.String(length=50), nullable=True),
        sa.Column('development_level', sa.String(length=50), nullable=True),
        sa.Column('predominant_building_type', sa.JSON(), nullable=True),
        sa.Column('is_tourist_area', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('tourist_attractions_nearby', sa.Text(), nullable=True),
        sa.Column('locality_description_text', sa.Text(), nullable=True),
        sa.Column('ownership_type', sa.String(length=200), nullable=True),
        sa.Column('street_lines_status', sa.String(length=200), nullable=True),
        sa.Column('building_limits_status', sa.String(length=200), nullable=True),
        sa.Column('local_authority_data', sa.Text(), nullable=True),
        sa.Column('rent_act_effectiveness', sa.String(length=200), nullable=True),
        sa.Column('title_search_conducted', sa.String(length=3), nullable=True),
        sa.Column('pedigree_search_conducted', sa.String(length=3), nullable=True),
        sa.Column('valuation_basis_note', sa.Text(), nullable=True),
        sa.Column('property_encumbered', sa.String(length=3), nullable=True),
        sa.Column('encumbrance_type', sa.String(length=100), nullable=True),
        sa.Column('encumbrance_details', sa.Text(), nullable=True),
        sa.Column('street_lines_gazette_ref', sa.String(length=100), nullable=True),
        sa.Column('street_lines_gazette_date', sa.String(length=20), nullable=True),
        sa.Column('street_lines_impact_description', sa.Text(), nullable=True),
        sa.Column('building_distance_from_road', sa.String(length=50), nullable=True),
        sa.Column('building_plan_approved', sa.String(length=20), nullable=True),
        sa.Column('building_plan_reference', sa.String(length=200), nullable=True),
        sa.Column('building_approval_authority', sa.String(length=200), nullable=True),
        sa.Column('building_within_limits', sa.String(length=3), nullable=True),
        sa.Column('local_authority_rated', sa.String(length=3), nullable=True),
        sa.Column('local_authority_tax_levy', sa.Text(), nullable=True),
        sa.Column('comparable_properties', sa.JSON(), nullable=True),
        sa.Column('land_market_analysis', sa.Text(), nullable=True),
        sa.Column('valuation_land_extent', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('valuation_rate_per_perch', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('valuation_total_land_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_buildings_data', sa.JSON(), nullable=True),
        sa.Column('valuation_total_buildings_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_addons', sa.JSON(), nullable=True),
        sa.Column('valuation_total_addons_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_market_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_forced_sale_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('valuation_forced_sale_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_insurance_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_manual_overrides', sa.JSON(), nullable=True),
        sa.Column('certification_text', sa.Text(), nullable=True),
        sa.Column('certificate_identity_confirmed', sa.Boolean(), server_default='false', nullable=True),
        sa.Column('certification_valuer_name', sa.String(length=300), nullable=True),
        sa.Column('certification_valuer_designation', sa.String(length=200), nullable=True),
        sa.Column('certification_date', sa.String(length=50), nullable=True),
        sa.Column('is_multi_property', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('property_count', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('total_valuation_amount', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('invoice_data', sa.JSON(), nullable=True),
        sa.Column('primary_vehicle_id', sa.Integer(), nullable=True),
        sa.Column('is_office_use', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('vehicle_count', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('folio_number', sa.String(length=100), nullable=True),
        sa.Column('inspection_place', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['primary_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)

    # ### Properties table ###
    op.create_table('properties',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='draft'),
        sa.Column('property_type', sa.String(length=50), nullable=False, server_default='residential'),
        sa.Column('lot_number', sa.String(length=200), nullable=True),
        sa.Column('plan_number', sa.String(length=100), nullable=True),
        sa.Column('plan_date', sa.String(length=50), nullable=True),
        sa.Column('licensed_surveyor_name', sa.String(length=255), nullable=True),
        sa.Column('property_identification_type', sa.String(length=50), nullable=True),
        sa.Column('property_identification_documents', sa.JSON(), nullable=True),
        sa.Column('has_deed_info', sa.String(length=10), nullable=True),
        sa.Column('deeds', sa.JSON(), nullable=True),
        sa.Column('assessment_number', sa.String(length=100), nullable=True),
        sa.Column('property_village', sa.String(length=200), nullable=True),
        sa.Column('property_divisional_secretariat', sa.String(length=200), nullable=True),
        sa.Column('property_district', sa.String(length=100), nullable=True),
        sa.Column('property_province', sa.String(length=100), nullable=True),
        sa.Column('property_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('property_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('property_number', sa.String(length=50), nullable=True),
        sa.Column('grama_niladari_division', sa.String(length=200), nullable=True),
        sa.Column('hathpaththuwa', sa.String(length=300), nullable=True),
        sa.Column('korale', sa.String(length=300), nullable=True),
        sa.Column('pradeshiya_sabha', sa.String(length=200), nullable=True),
        sa.Column('ward_number', sa.String(length=20), nullable=True),
        sa.Column('is_municipal_limit', sa.Boolean(), nullable=True),
        sa.Column('location_direction', sa.String(length=50), nullable=True),
        sa.Column('access_starting_point_name', sa.Text(), nullable=True),
        sa.Column('access_starting_point_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column('access_starting_point_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
        sa.Column('access_route_data', sa.JSON(), nullable=True),
        sa.Column('access_directions_text', sa.Text(), nullable=True),
        sa.Column('access_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('access_duration_minutes', sa.Integer(), nullable=True),
        sa.Column('access_road_type', sa.String(length=200), nullable=True),
        sa.Column('property_road_position', sa.String(length=100), nullable=True),
        sa.Column('location_map_image_data', sa.Text(), nullable=True),
        sa.Column('access_road_conditions', sa.JSON(), nullable=True),
        sa.Column('access_entry_mode', sa.String(length=20), nullable=True),
        sa.Column('access_road_classes_detected', sa.JSON(), nullable=True),
        sa.Column('land_extent_acres', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('land_extent_roods', sa.Integer(), nullable=True),
        sa.Column('land_extent_perches', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('land_extent_hectares', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('land_extent_square_meters', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('land_extent_formatted', sa.String(length=50), nullable=True),
        sa.Column('land_traditional_name', sa.String(length=300), nullable=True),
        sa.Column('boundaries', sa.JSON(), nullable=True),
        sa.Column('physical_boundaries_types', sa.JSON(), nullable=True),
        sa.Column('physical_boundaries_description', sa.Text(), nullable=True),
        sa.Column('boundary_types_per_direction', sa.JSON(), nullable=True),
        sa.Column('entrance_type', sa.String(length=100), nullable=True),
        sa.Column('boundaries_summary_text', sa.Text(), nullable=True),
        sa.Column('has_multiple_lots', sa.Boolean(), nullable=True),
        sa.Column('lots_data', sa.JSON(), nullable=True),
        sa.Column('land_shape', sa.String(length=50), nullable=True),
        sa.Column('land_type', sa.String(length=50), nullable=True),
        sa.Column('land_frontage_type', sa.String(length=100), nullable=True),
        sa.Column('land_frontage_width', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('land_frontage_description', sa.Text(), nullable=True),
        sa.Column('land_level', sa.String(length=50), nullable=True),
        sa.Column('land_level_difference', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('soil_type', sa.String(length=50), nullable=True),
        sa.Column('water_table_depth', sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column('flood_risk', sa.String(length=50), nullable=True),
        sa.Column('inundation_risk', sa.String(length=50), nullable=True),
        sa.Column('earth_slip_risk', sa.String(length=50), nullable=True),
        sa.Column('land_condition', sa.String(length=50), nullable=True),
        sa.Column('land_condition_description', sa.Text(), nullable=True),
        sa.Column('land_description_text', sa.Text(), nullable=True),
        sa.Column('elevation_changes', sa.String(length=50), nullable=True),
        sa.Column('drainage_pattern', sa.String(length=50), nullable=True),
        sa.Column('vegetation_type', sa.String(length=50), nullable=True),
        sa.Column('natural_features', sa.Text(), nullable=True),
        sa.Column('buildings', sa.JSON(), nullable=True),
        sa.Column('occupier_name', sa.String(length=300), nullable=True),
        sa.Column('occupier_relationship', sa.String(length=50), nullable=True),
        sa.Column('property_photos', sa.JSON(), nullable=True),
        sa.Column('distance_to_major_town_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('major_town_name', sa.String(length=200), nullable=True),
        sa.Column('nearby_facilities', sa.JSON(), nullable=True),
        sa.Column('has_electricity', sa.Boolean(), nullable=True),
        sa.Column('water_supply_type', sa.JSON(), nullable=True),
        sa.Column('telecommunication_types', sa.JSON(), nullable=True),
        sa.Column('internet_types', sa.JSON(), nullable=True),
        sa.Column('has_public_transport', sa.Boolean(), nullable=True),
        sa.Column('public_transport_routes', sa.Text(), nullable=True),
        sa.Column('public_transport_frequency', sa.String(length=200), nullable=True),
        sa.Column('nearest_bus_stop_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('nearest_bus_stop_name', sa.String(length=200), nullable=True),
        sa.Column('nearest_railway_station', sa.String(length=200), nullable=True),
        sa.Column('nearest_railway_distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column('area_type', sa.String(length=50), nullable=True),
        sa.Column('development_level', sa.String(length=50), nullable=True),
        sa.Column('predominant_building_type', sa.JSON(), nullable=True),
        sa.Column('is_tourist_area', sa.Boolean(), nullable=True),
        sa.Column('tourist_attractions_nearby', sa.Text(), nullable=True),
        sa.Column('locality_description_text', sa.Text(), nullable=True),
        sa.Column('ownership_type', sa.String(length=200), nullable=True),
        sa.Column('street_lines_status', sa.String(length=200), nullable=True),
        sa.Column('street_lines_gazette_ref', sa.String(length=100), nullable=True),
        sa.Column('street_lines_gazette_date', sa.String(length=20), nullable=True),
        sa.Column('street_lines_impact_description', sa.Text(), nullable=True),
        sa.Column('building_limits_status', sa.String(length=200), nullable=True),
        sa.Column('building_distance_from_road', sa.String(length=50), nullable=True),
        sa.Column('building_plan_approved', sa.String(length=20), nullable=True),
        sa.Column('building_plan_reference', sa.String(length=200), nullable=True),
        sa.Column('building_approval_authority', sa.String(length=200), nullable=True),
        sa.Column('building_within_limits', sa.String(length=3), nullable=True),
        sa.Column('local_authority_data', sa.Text(), nullable=True),
        sa.Column('local_authority_rated', sa.String(length=3), nullable=True),
        sa.Column('local_authority_tax_levy', sa.Text(), nullable=True),
        sa.Column('rent_act_effectiveness', sa.String(length=200), nullable=True),
        sa.Column('title_search_conducted', sa.String(length=3), nullable=True),
        sa.Column('pedigree_search_conducted', sa.String(length=3), nullable=True),
        sa.Column('valuation_basis_note', sa.Text(), nullable=True),
        sa.Column('property_encumbered', sa.String(length=3), nullable=True),
        sa.Column('encumbrance_type', sa.String(length=100), nullable=True),
        sa.Column('encumbrance_details', sa.Text(), nullable=True),
        sa.Column('comparable_properties', sa.JSON(), nullable=True),
        sa.Column('land_market_analysis', sa.Text(), nullable=True),
        sa.Column('valuation_land_extent', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('valuation_rate_per_perch', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('valuation_total_land_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_buildings_data', sa.JSON(), nullable=True),
        sa.Column('valuation_total_buildings_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_addons', sa.JSON(), nullable=True),
        sa.Column('valuation_total_addons_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_market_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_forced_sale_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('valuation_forced_sale_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_insurance_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('valuation_manual_overrides', sa.JSON(), nullable=True),
        sa.Column('property_owner_title', sa.String(length=20), nullable=True),
        sa.Column('property_owner_full_name', sa.String(length=500), nullable=True),
        sa.Column('property_owner_id_type', sa.String(length=50), nullable=True),
        sa.Column('property_owner_id_number', sa.String(length=100), nullable=True),
        sa.Column('has_additional_owner', sa.String(length=10), nullable=True),
        sa.Column('additional_owner_names', sa.Text(), nullable=True),
        sa.Column('inspection_date', sa.String(length=50), nullable=True),
        sa.Column('uploaded_documents', sa.JSON(), nullable=True),
        sa.Column('field_sources', sa.JSON(), nullable=True),
        sa.Column('survey_plan_scale', sa.String(length=50), nullable=True),
        sa.Column('plan_reference_notes', sa.Text(), nullable=True),
        sa.Column('is_template', sa.Boolean(), nullable=True, server_default='false'),
        sa.Column('template_name', sa.String(length=200), nullable=True),
        sa.Column('last_valued_date', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)

    # ### Jobs table ###
    op.create_table('jobs',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=True),
        sa.Column('job_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
        sa.Column('result_url', sa.String(length=500), nullable=True),
        sa.Column('result_filename', sa.String(length=255), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('progress_percent', sa.Integer(), nullable=True, server_default='0'),
        sa.Column('progress_message', sa.String(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # ### Report Properties junction table ###
    op.create_table('report_properties',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('property_id', sa.Integer(), nullable=False),
        sa.Column('property_order', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('report_specific_notes', sa.Text(), nullable=True),
        sa.Column('override_market_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('override_forced_sale_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_properties_id'), 'report_properties', ['id'], unique=False)
    op.create_index(op.f('ix_report_properties_property_id'), 'report_properties', ['property_id'], unique=False)
    op.create_index(op.f('ix_report_properties_report_id'), 'report_properties', ['report_id'], unique=False)

    # ### Report Vehicles junction table ###
    op.create_table('report_vehicles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_order', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('report_specific_notes', sa.Text(), nullable=True),
        sa.Column('override_market_value', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_vehicles_id'), 'report_vehicles', ['id'], unique=False)

    # ### Audit Logs table ###
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('action', sa.String(length=50), nullable=False),
        sa.Column('resource_type', sa.String(length=50), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.Column('user_agent', sa.String(length=500), nullable=True),
        sa.Column('request_id', sa.String(length=36), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)


def downgrade() -> None:
    # Drop tables in reverse order of creation (respecting foreign key dependencies)
    op.drop_table('audit_logs')
    op.drop_table('report_vehicles')
    op.drop_table('report_properties')
    op.drop_table('jobs')
    op.drop_table('properties')
    op.drop_table('reports')
    op.drop_table('vehicles')
    op.drop_table('users')
